import {createPublicKey,verify,createHash} from 'node:crypto';
export const REPO='zunderlabs/zunder-guard', NAME='No-key original Mac reboot capability', JOB='original-mac-arm-target';
export const authority=Object.freeze({sourceAdmitted:false,runtimeAdmitted:false,nativeReleaseAccepted:false,releaseReady:false,privateCustodyProven:false,wholeResourceCleanupProven:false});
export function fail(){throw Error('REFUSED');}
export function exact(o,keys){if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).sort().join('|')!==[...keys].sort().join('|'))fail();}
export function canonical(o){if(Array.isArray(o))return '['+o.map(canonical).join(',')+']'; if(o&&typeof o==='object')return '{'+Object.keys(o).sort().map(k=>JSON.stringify(k)+':'+canonical(o[k])).join(',')+'}'; return JSON.stringify(o);}
export function closedJSON(raw,max=32768){if(typeof raw!=='string'||Buffer.byteLength(raw)>max)fail();let o;try{o=JSON.parse(raw);}catch{fail();}if(canonical(o)!==raw)fail();return o;}
const uint=n=>Number.isSafeInteger(n)&&n>=0, hex=s=>typeof s==='string'&&/^[0-9a-f]{64}$/.test(s), uuid=s=>typeof s==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(s)&&!/^0{8}-0{4}-0{4}-0{4}-0{12}$/.test(s);
export function context(c){exact(c,['repository','head','run','attempt','job','nonce']);if(c.repository!==REPO||!(/^[0-9a-f]{40}$/.test(c.head))||![c.run,c.attempt,c.job].every(n=>uint(n)&&n>0)||!hex(c.nonce))fail();return c;}
export function facts(f,wall){exact(f,['machine','boot','boot_ms','uptime_ms','pid','birth_ms']);if(!hex(f.machine)||!uuid(f.boot)||![f.boot_ms,f.uptime_ms,f.pid,f.birth_ms].every(uint)||f.pid===0||f.boot_ms===0||f.birth_ms<f.boot_ms||f.birth_ms>wall||f.boot_ms>wall||f.uptime_ms>wall-f.boot_ms+5000)fail();}
export function envelope(e,key){exact(e,['payload','signature']);if(!/^[A-Za-z0-9+/]+={0,2}$/.test(e.payload)||!(/^[A-Za-z0-9+/]+={0,2}$/.test(e.signature)))fail();let b=Buffer.from(e.payload,'base64'),sig=Buffer.from(e.signature,'base64');if(b.toString('base64')!==e.payload||sig.toString('base64')!==e.signature||sig.length!==64||b.length>16384)fail();let k=Buffer.from(key,'base64');if(k.length!==32||k.toString('base64')!==key)fail();const pub=createPublicKey({key:Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),k]),format:'der',type:'spki'});if(!verify(null,b,pub,sig))fail();return closedJSON(b.toString('utf8'),16384);}
export function preboot(e,key,expected){const p=envelope(e,key);exact(p,['schema','phase','context','key','wall_ms','observe_deadline_ms','cleanup_deadline_ms','facts','source','binary','files','authority']);if(canonical(p.authority)!==canonical(authority))fail();if(p.schema!==1||p.phase!=='PREBOOT'||p.key!==key||canonical(context(p.context))!==canonical(context(expected))||!uint(p.wall_ms)||p.observe_deadline_ms!==p.wall_ms+720000||p.cleanup_deadline_ms!==p.wall_ms+900000||!hex(p.source)||!hex(p.binary))fail();facts(p.facts,p.wall_ms);exact(p.files,['binary','config','key','token','plist']);for(const [name,d] of Object.entries(p.files)){exact(d,['dev','ino','mode','sha']);if(!uint(d.dev)||!uint(d.ino)||d.ino===0||d.mode!==(name==='binary'?493:384)||!hex(d.sha))fail();}return p;}
export function postboot(e,key,p){const q=envelope(e,key);exact(q,['schema','phase','context','key','wall_ms','facts','source','binary','preboot_sha','cleanup','authority']);if(canonical(q.authority)!==canonical(authority))fail();if(q.schema!==1||q.phase!=='POSTBOOT'||q.key!==key||canonical(q.context)!==canonical(p.context)||!uint(q.wall_ms)||q.wall_ms<p.wall_ms||q.wall_ms>=p.observe_deadline_ms||q.source!==p.source||q.binary!==p.binary||!hex(q.preboot_sha))fail();facts(q.facts,q.wall_ms);if(q.facts.machine!==p.facts.machine||q.facts.boot===p.facts.boot||q.facts.boot_ms<=p.facts.boot_ms||q.facts.birth_ms<=p.facts.birth_ms||q.facts.uptime_ms>120000)fail();exact(q.cleanup,['binary','config','key','token','plist','registration','service','self_exit','vm']);for(const [k,v]of Object.entries(q.cleanup)){if(['service','self_exit','vm'].includes(k)?v!=='UNKNOWN':!['ABSENT_OBSERVED','UNKNOWN'].includes(v))fail();}return q;}
export function bundle(raw,expected){const b=closedJSON(raw);exact(b,b.phase==='PREBOOT'?['schema','phase','key','preboot']:['schema','phase','key','preboot','postboot']);if(b.schema!==1||!['PREBOOT','POSTBOOT'].includes(b.phase))fail();const p=preboot(b.preboot,b.key,expected);let q;if(b.phase==='POSTBOOT'){q=postboot(b.postboot,b.key,p);if(q.preboot_sha!==createHash('sha256').update(canonical(b.preboot)).digest('hex'))fail();}return {b,p,q};}
export function originalClock(sample=()=>({wall:Date.now(),mono:process.hrtime.bigint()})){const origin=sample();let last=origin,bad=false;return Object.freeze({read(limit=720000){const now=sample();if(bad||now.wall<last.wall||now.mono<last.mono||now.wall<origin.wall||now.mono<origin.mono){bad=true;fail();}last=now;const age=Math.max(now.wall-origin.wall,Number((now.mono-origin.mono)/1000000n));if(age>=limit)fail();return {wall:now.wall,age,remaining:limit-age};}});}
