import {readFile,writeFile,mkdir,mkdtemp,chmod} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import {inflateRawSync} from 'node:zlib';
import {canonical} from './protocol.mjs';
import {exact,requireTrue,digest,readAppliedScope} from './relay-schema.mjs';
import {OriginalJournal} from './journal.mjs';
import {OriginalPublicController,sampleOriginalOrigin} from './controller.mjs';
import {ownedModules,originalMacBootstrap} from './bootstrap-macos.mjs';

const sourceDirectory=dirname(fileURLToPath(import.meta.url));
const nativeFiles=['macos_process.c','macos_process.h','macos_observer.swift'];
async function bounded(response,maximum){requireTrue(response.ok);const reader=response.body.getReader(),parts=[];let size=0;while(true){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>maximum){await reader.cancel();throw new Error('Body bound refused');}parts.push(part.value);}const out=new Uint8Array(size);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length;}return out;}
async function api(path){requireTrue(path.startsWith('/repos/zunderlabs/zunder-guard/'));const response=await fetch('https://api.github.com'+path,{headers:{accept:'application/vnd.github+json',authorization:'Bearer '+process.env.GITHUB_TOKEN,'x-github-api-version':'2022-11-28'},redirect:'error',signal:AbortSignal.timeout(5000)});return JSON.parse(new TextDecoder().decode(await bounded(response,262144)));}
function expectedScope(){const value=JSON.parse(process.env.PUBLIC_REBOOT_EXPECTED_SCOPE??'null');exact(value,['origin','deployment_sha256','source','workflow_ref','repository_id','owner_id','audience']);requireTrue(value.source===process.env.GITHUB_SHA);return value;}
async function oidc(){const base=new URL(process.env.ACTIONS_ID_TOKEN_REQUEST_URL);requireTrue(base.protocol==='https:'&&base.hostname.endsWith('.actions.githubusercontent.com'));base.searchParams.set('audience','zunder-public-reboot');const response=await fetch(base,{headers:{authorization:'Bearer '+process.env.ACTIONS_ID_TOKEN_REQUEST_TOKEN},redirect:'error',signal:AbortSignal.timeout(5000)});const value=JSON.parse(new TextDecoder().decode(await bounded(response,24576)));requireTrue(typeof value.value==='string');return value.value;}
async function inventory(){return Promise.all(ownedModules.map(async name=>({name,sha256:await digest(await readFile(join(sourceDirectory,name)))})));}
async function nativeInventory(){return Promise.all(nativeFiles.map(async name=>({name,sha256:await digest(await readFile(join(sourceDirectory,'native',name)))})));}
async function targetJob(){const run=Number(process.env.GITHUB_RUN_ID),attempt=Number(process.env.GITHUB_RUN_ATTEMPT);const result=await api(`/repos/zunderlabs/zunder-guard/actions/runs/${run}/attempts/${attempt}/jobs?per_page=100`);requireTrue(result.total_count<=100&&result.jobs.length===result.total_count);const targets=result.jobs.filter(job=>job.name==='target / target-reboot');requireTrue(targets.length===1&&targets[0].status==='in_progress'&&targets[0].head_sha===process.env.GITHUB_SHA&&targets[0].run_id===run&&targets[0].labels.includes('macos-15'));return targets[0].id;}
async function command(path,args){const child=spawn(path,args,{stdio:['ignore','ignore','ignore'],env:{PATH:'/usr/bin:/bin',LANG:'C'},cwd:sourceDirectory,timeout:90000,killSignal:'SIGKILL'});await new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',(code,signal)=>code===0&&signal===null?resolve():reject(new Error('Fixed build refused')));});}
export function decodeDescriptorZip(raw){
  const b=Buffer.from(raw);requireTrue(b.length>=22&&b.length<=65536);let end=-1;
  for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--)if(b.readUInt32LE(i)===0x06054b50){end=i;break;}
  requireTrue(end>=0&&b.readUInt16LE(end+4)===0&&b.readUInt16LE(end+6)===0&&b.readUInt16LE(end+8)===1&&b.readUInt16LE(end+10)===1&&b.readUInt16LE(end+20)===0&&end+22===b.length);
  const central=b.readUInt32LE(end+16);requireTrue(b.readUInt32LE(central)===0x02014b50&&central+b.readUInt32LE(end+12)===end);
  const flags=b.readUInt16LE(central+8),method=b.readUInt16LE(central+10),compressed=b.readUInt32LE(central+20),size=b.readUInt32LE(central+24),nameLength=b.readUInt16LE(central+28),extraLength=b.readUInt16LE(central+30),commentLength=b.readUInt16LE(central+32),local=b.readUInt32LE(central+42);
  requireTrue((flags&~0x808)===0&&[0,8].includes(method)&&size<=8192&&compressed<=16384&&b.subarray(central+46,central+46+nameLength).toString()==='descriptor.json'&&central+46+nameLength+extraLength+commentLength===end&&b.readUInt32LE(local)===0x04034b50);
  requireTrue(b.readUInt16LE(local+6)===flags&&b.readUInt16LE(local+8)===method);const ln=b.readUInt16LE(local+26),le=b.readUInt16LE(local+28),start=local+30+ln+le;requireTrue(b.subarray(local+30,local+30+ln).toString()==='descriptor.json'&&start+compressed<=central);
  const data=method===0?b.subarray(start,start+compressed):inflateRawSync(b.subarray(start,start+compressed),{maxOutputLength:8192});requireTrue(data.length===size);
  let crc=0xffffffff;for(const byte of data){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}requireTrue(((crc^0xffffffff)>>>0)===b.readUInt32LE(central+16));
  return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(data));
}
async function actualDescriptor(firstOrigin){
  const run=Number(process.env.GITHUB_RUN_ID),attempt=Number(process.env.GITHUB_RUN_ATTEMPT);const actualRun=await api(`/repos/zunderlabs/zunder-guard/actions/runs/${run}/attempts/${attempt}`);requireTrue(actualRun.head_sha===process.env.GITHUB_SHA&&actualRun.run_attempt===attempt);
  for(let count=0;count<100;count++){
    requireTrue(Date.now()>=firstOrigin.wall&&Date.now()<firstOrigin.wall+720000&&process.hrtime.bigint()<firstOrigin.mono+720000000000n);
    const listing=await api(`/repos/zunderlabs/zunder-guard/actions/runs/${run}/artifacts?per_page=100`);requireTrue(listing.total_count<=100&&listing.artifacts.length===listing.total_count);
    const artifacts=listing.artifacts.filter(a=>a.name==='public-reboot-target-inventory');
    if(artifacts.length){requireTrue(artifacts.length===1);const a=artifacts[0];requireTrue(!a.expired&&a.size_in_bytes<=65536&&a.workflow_run.id===run&&a.workflow_run.head_sha===process.env.GITHUB_SHA&&Date.parse(a.created_at)>=Date.parse(actualRun.run_started_at)&&/^sha256:[0-9a-f]{64}$/.test(a.digest));
      const first=await fetch(`https://api.github.com/repos/zunderlabs/zunder-guard/actions/artifacts/${a.id}/zip`,{headers:{authorization:'Bearer '+process.env.GITHUB_TOKEN},redirect:'manual',signal:AbortSignal.timeout(5000)});requireTrue(first.status===302);const url=new URL(first.headers.get('location'));requireTrue(url.protocol==='https:'&&url.username===''&&url.password===''&&/^[a-z0-9]+\.blob\.core\.windows\.net$/.test(url.hostname));
      const raw=await bounded(await fetch(url,{redirect:'error',signal:AbortSignal.timeout(5000)}),65536);requireTrue('sha256:'+await digest(raw)===a.digest);return decodeDescriptorZip(raw);
    }await new Promise(resolve=>setTimeout(resolve,3000));
  }throw new Error('Original descriptor unavailable');
}
export async function controllerMain(output){
  requireTrue(process.platform==='linux'&&process.env.GITHUB_REPOSITORY==='zunderlabs/zunder-guard');const first=sampleOriginalOrigin();const expected=expectedScope(),scope=await readAppliedScope(expected);const descriptor=await actualDescriptor(first);
  exact(descriptor,['schema','kind','run_id','attempt','source','target_job_id','helper_sha256','runtime_sha256','source_files','native_sources']);
  requireTrue(descriptor.schema===1&&descriptor.kind==='public-macos-helper-runtime-inventory'&&descriptor.run_id===Number(process.env.GITHUB_RUN_ID)&&descriptor.attempt===Number(process.env.GITHUB_RUN_ATTEMPT)&&descriptor.source===process.env.GITHUB_SHA&&descriptor.target_job_id===await targetJob()&&descriptor.runtime_sha256===process.env.PUBLIC_REBOOT_MAC_NODE_SHA256&&canonical(descriptor.source_files)===canonical(await inventory())&&canonical(descriptor.native_sources)===canonical(await nativeInventory()));
  const session=(await import('node:crypto')).randomBytes(32).toString('hex');const binding={run_id:descriptor.run_id,attempt:descriptor.attempt,source:descriptor.source,target_job_id:descriptor.target_job_id,label:'macos-15',session,helper_sha256:descriptor.helper_sha256,inventory_sha256:await digest(canonical(descriptor.source_files))};
  const parent=await mkdtemp(join(tmpdir(),'public-reboot-original-'));await chmod(parent,0o700);const journal=await OriginalJournal.create(parent,session);
  const controller=new OriginalPublicController({scope,binding,journal,firstOrigin:first});let report;
  try {await controller.enrollController(await oidc());let ready=false;for(let count=0;count<100;count++){controller.assertLive();const ack=await controller.observeEnrollment();if(ack.observer_public_key!==null){ready=true;break;}await new Promise(resolve=>setTimeout(resolve,3000));}requireTrue(ready);
    for(let phase=0;phase<4;phase++){await controller.challenge();let observed=false;for(let count=0;count<180;count++){report=await controller.poll();if(report.observed_sequence===phase+1){observed=true;break;}await new Promise(resolve=>setTimeout(resolve,3000));}requireTrue(observed);}
  }catch{report=controller.report();report.outcome='UNKNOWN';}
  report??=controller.report();await writeFile(output,canonical(report)+'\n',{mode:0o600});return report;
}
export async function prepareTarget(output,helper){requireTrue(process.platform==='darwin'&&process.arch==='arm64'&&process.env.GITHUB_REPOSITORY==='zunderlabs/zunder-guard');await readAppliedScope(expectedScope());requireTrue(await digest(await readFile(process.execPath))===process.env.PUBLIC_REBOOT_MAC_NODE_SHA256);
  const object=helper+'.o';await command('/usr/bin/xcrun',['clang','-O2','-Wall','-Wextra','-Werror','-c',join(sourceDirectory,'native/macos_process.c'),'-o',object]);await command('/usr/bin/xcrun',['swiftc','-O','-import-objc-header',join(sourceDirectory,'native/macos_process.h'),join(sourceDirectory,'native/macos_observer.swift'),object,'-o',helper]);
  const value={schema:1,kind:'public-macos-helper-runtime-inventory',run_id:Number(process.env.GITHUB_RUN_ID),attempt:Number(process.env.GITHUB_RUN_ATTEMPT),source:process.env.GITHUB_SHA,target_job_id:await targetJob(),helper_sha256:await digest(await readFile(helper)),runtime_sha256:process.env.PUBLIC_REBOOT_MAC_NODE_SHA256,source_files:await inventory(),native_sources:await nativeInventory()};await writeFile(output,canonical(value)+'\n',{mode:0o600});
}
async function waitBootstrap(scope){for(let count=0;count<180;count++){const response=await fetch(scope.origin.replace(/\/$/,'')+'/api/waitlist/ci-reboot/bootstrap',{redirect:'error',cache:'no-store',signal:AbortSignal.timeout(5000)});if(response.status===200){const value=JSON.parse(new TextDecoder().decode(await bounded(response,8192)));exact(value,['schema','kind','binding','origin','version','sequence','github_enrollment_verified','jobs_identity_verified']);requireTrue(value.schema===1&&value.kind==='actual-original-public-reboot-bootstrap'&&value.github_enrollment_verified&&value.jobs_identity_verified&&value.version===1&&value.sequence===0);return value;}requireTrue(response.status===409);await new Promise(resolve=>setTimeout(resolve,3000));}throw new Error('Original bootstrap missing');}
export async function targetMain(descriptorPath,helper){const descriptor=JSON.parse(await readFile(descriptorPath,'utf8'));const expected=expectedScope(),scope=await readAppliedScope(expected);const value=await waitBootstrap(scope);requireTrue(value.binding.run_id===Number(process.env.GITHUB_RUN_ID)&&value.binding.attempt===Number(process.env.GITHUB_RUN_ATTEMPT)&&value.binding.source===process.env.GITHUB_SHA&&value.binding.target_job_id===descriptor.target_job_id&&value.binding.helper_sha256===descriptor.helper_sha256&&value.binding.inventory_sha256===await digest(canonical(await inventory())));
  const input={plan:{binding:value.binding,origin:value.origin},expected_scope:expected,source_directory:sourceDirectory,source_files:descriptor.source_files,helper_path:resolve(helper),helper_sha256:descriptor.helper_sha256,runtime_path:process.execPath,runtime_sha256:descriptor.runtime_sha256,target_jwt:await oidc()};
  const child=spawn('/usr/bin/sudo',['-n','--',process.execPath,fileURLToPath(import.meta.url),'root-bootstrap'],{env:{PATH:'/usr/bin:/bin',LANG:'C'},cwd:'/',stdio:['pipe','ignore','ignore']});child.stdin.end(canonical(input));input.target_jwt='';await new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',(code,signal)=>code===0&&signal===null?resolve():reject(new Error('Original target result UNKNOWN')));});
}
async function stdinJSON(){const parts=[];let size=0;for await(const part of process.stdin){size+=part.length;requireTrue(size<=32768);parts.push(part);}return JSON.parse(Buffer.concat(parts).toString('utf8'));}
if(import.meta.url===`file://${process.argv[1]}`){try{const mode=process.argv[2];if(mode==='controller'&&process.argv.length===4)await controllerMain(resolve(process.argv[3]));else if(mode==='prepare-target'&&process.argv.length===5)await prepareTarget(resolve(process.argv[3]),resolve(process.argv[4]));else if(mode==='target'&&process.argv.length===5)await targetMain(resolve(process.argv[3]),resolve(process.argv[4]));else if(mode==='root-bootstrap'&&process.argv.length===3)await originalMacBootstrap(await stdinJSON());else throw new Error('Closed mode refused');}catch{if(process.argv[2]==='controller'&&process.argv.length===4){try{await writeFile(resolve(process.argv[3]),canonical({kind:'public-reboot-original-preflight-unknown',outcome:'UNKNOWN',release_ready:false,native_credential_retention_proven:false,all_owned_processes_gone:false})+'\n',{mode:0o600,flag:'wx'});}catch{}}process.stderr.write('Public reboot experiment refused or UNKNOWN\n');process.exitCode=1;}}
