import test from 'node:test';
import assert from 'node:assert/strict';
import {canonical} from '../protocol.mjs';
import {readAppliedScope,digest} from '../relay-schema.mjs';
import {RelayClient} from '../relay-client.mjs';
import {OriginalPublicController,sampleOriginalOrigin} from '../controller.mjs';
import {registrationAbsent,registrationMatches} from '../macos-owned.mjs';
import {plistText} from '../bootstrap-macos.mjs';
import {decodeDescriptorZip} from '../runtime-cli.mjs';

const expected={origin:'https://reboot-fixture.invalid',deployment_sha256:'d'.repeat(64),source:'a'.repeat(40),workflow_ref:'zunderlabs/zunder-guard/.github/workflows/public-reboot.yml@refs/heads/main',repository_id:'1409357189',owner_id:'338317604',audience:'zunder-public-reboot'};
async function scope(){return readAppliedScope(expected,{fetchImpl:async()=>new Response(canonical({schema:1,kind:'applied-public-reboot-relay-scope',...expected,expires_ms:Date.now()+1000000,enabled:true}),{headers:{'content-type':'application/json'}})});}
const binding={run_id:123,attempt:1,source:expected.source,target_job_id:456,label:'macos-15',session:'b'.repeat(64),helper_sha256:'c'.repeat(64),inventory_sha256:'d'.repeat(64)};
const wall=Date.now(),origin={wall_ms:wall,observe_until_ms:wall+720000,cleanup_until_ms:wall+900000};
const request={schema:1,kind:'public-reboot-relay-request',operation:'challenge',binding,origin,expected_version:2,expected_sequence:0,nonce:'1'.repeat(64),observer_public_key:null,event:null,signature:null,jwt:null,controller_public_key:'2'.repeat(64),controller_signature:'3'.repeat(128)};
test('lost mutation response consumes original dispatch before I/O and cannot retry',async()=>{let calls=0;const client=new RelayClient(await scope(),{assertLive(){},fetchImpl:async()=>{calls++;throw new Error('INERT-lost-response')}});await assert.rejects(client.request(request));await assert.rejects(client.request(request));assert.equal(calls,1);});
test('fixed origin, no redirects and no ambient credential request',async()=>{let observed;const client=new RelayClient(await scope(),{assertLive(){},fetchImpl:async(url,options)=>{observed={url,options};const value={schema:1,kind:'actual-public-reboot-relay-ack',request_sha256:await digest(options.body),binding,origin,version:3,sequence:0,state:'ENROLLED',nonce:request.nonce,observer_public_key:'4'.repeat(64),event:null,signature:null,github_enrollment_verified:true,jobs_identity_verified:true};return new Response(canonical(value),{headers:{'content-type':'application/json'}});}});await client.request(request);assert.equal(observed.url,expected.origin+'/api/waitlist/ci-reboot/challenge');assert.equal(observed.options.redirect,'error');assert.equal(observed.options.credentials,'omit');assert.equal(observed.options.headers.authorization,undefined);});
test('oversize body and wrong provider source are UNKNOWN',async()=>{const client=new RelayClient(await scope(),{assertLive(){},fetchImpl:async()=>new Response('x'.repeat(16385),{headers:{'content-type':'application/json'}})});await assert.rejects(client.request(request));const other=new RelayClient(await scope(),{assertLive(){},fetchImpl:async()=>new Response(canonical({...request,binding:{...binding,source:'f'.repeat(40)}}),{headers:{'content-type':'application/json'}})});await assert.rejects(other.request(request));});
test('scope admission refuses redirected, missing and wrong deployment readback',async()=>{await assert.rejects(readAppliedScope(expected,{fetchImpl:async()=>new Response(null,{status:302})}));await assert.rejects(readAppliedScope(expected,{fetchImpl:async()=>new Response(canonical({schema:1,kind:'applied-public-reboot-relay-scope',...expected,deployment_sha256:'0'.repeat(64),expires_ms:Date.now()+1000000,enabled:true}),{headers:{'content-type':'application/json'}})}));});
test('original controller rollback remains HOLD even after later forward sample',async()=>{const first=sampleOriginalOrigin();let wall=first.wall,mono=first.mono;const controller=new OriginalPublicController({scope:await scope(),binding,journal:{append:async()=>{},hold:async()=>{}},firstOrigin:first,clocks:{wall:()=>wall,mono:()=>mono}});wall+=1000;mono+=1000000n;controller.assertLive();wall-=1;assert.throws(()=>controller.assertLive());wall+=2;assert.throws(()=>controller.assertLive());assert.equal(controller.report().held,true);});
test('copied first origin cannot create a replacement controller',async()=>{const first=sampleOriginalOrigin(),admitted=await scope();assert.throws(()=>new OriginalPublicController({scope:admitted,binding,journal:{},firstOrigin:{...first}}));});
test('LaunchDaemon has one boot wrapper, clean fixed environment and no restart loop',()=>{const plan={label:'com.zunder.public-reboot.'+binding.session,runtime:'/Library/ZunderPublicReboot/'+binding.session+'/node',directory:'/Library/ZunderPublicReboot/'+binding.session};const plist=plistText(plan);assert.match(plist,/<key>RunAtLoad<\/key><true\/>/);assert.match(plist,/<key>KeepAlive<\/key><false\/>/);assert.match(plist,/<key>AbandonProcessGroup<\/key><true\/>/);assert.doesNotMatch(plist,/GITHUB|AWS|TOKEN|SECRET|keychain/i);});
test('owned registration parser refuses changed command, extra argument and unknown absence',()=>{const plan={directory:'/Library/ZunderPublicReboot/'+binding.session,runtime:'/Library/ZunderPublicReboot/'+binding.session+'/node',plist:'/Library/LaunchDaemons/fixture.plist'};const output=`path = ${plan.plist}\nprogram = ${plan.runtime}\narguments = {\n${plan.runtime}\n${plan.directory}/boot-wrapper.mjs\n${plan.directory}/plan.json\n}\n`;assert.equal(registrationMatches(output,plan),true);assert.equal(registrationMatches(output.replace('program = '+plan.runtime,'program = /foreign'),plan),false);assert.equal(registrationMatches(output.replace('\n}\n','\n/foreign\n}\n'),plan),false);assert.equal(registrationAbsent({code:1,stderr:'Permission denied'},'fixture'),false);assert.equal(registrationAbsent({code:113,stderr:'Could not find service "fixture" in domain for system'},'fixture'),true);});
test('descriptor archive refuses malformed and oversized input',()=>{assert.throws(()=>decodeDescriptorZip(Buffer.alloc(22)));assert.throws(()=>decodeDescriptorZip(Buffer.alloc(65537)));});

test('all pending challenge shapes bind preceding event phase, sequence, binding and fresh nonce',async()=>{
  const {validateResponse}=await import('../relay-schema.mjs');
  const event={schema:1,kind:'public-host-reboot-observation',phase:'PREBOOT',sequence:0,nonce:'6'.repeat(64),binding,machine_sha256:'2'.repeat(64),marker_sha256:'3'.repeat(64),boot_id:'FIXTURE-PRE',boot_time_ms:100000,uptime_ms:1000,observer_pid:100,observer_birth:'100:1',cleanup:{registration_absent:false,files_absent:false,key_store_absent:false,observer_child_gone:false,carrier_exit_observed:false}};
  const read={...request,operation:'readback',expected_version:4,expected_sequence:1,nonce:null,controller_public_key:null,controller_signature:null};
  const ack={schema:1,kind:'actual-public-reboot-relay-ack',request_sha256:'0'.repeat(64),binding,origin,version:5,sequence:1,state:'PREBOOT',nonce:'7'.repeat(64),observer_public_key:'4'.repeat(64),event,signature:'5'.repeat(128),github_enrollment_verified:true,jobs_identity_verified:true};
  assert.equal(validateResponse(ack,read,ack.request_sha256).version,5);
  for(const changed of [{...ack,nonce:null},{...ack,nonce:event.nonce},{...ack,state:'ARMED'},{...ack,event:{...event,binding:{...binding,source:'f'.repeat(40)}}},{...ack,event:{...event,phase:'ARMED',sequence:1}},{...ack,sequence:3},{...ack,version:6}])assert.throws(()=>validateResponse(changed,read,ack.request_sha256));
});
